# Generated by Django 4.1.3 on 2022-11-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_twitter_author_name_alter_twitter_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='author_username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
