# Generated by Django 4.1.3 on 2022-11-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_twitter_link_to_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='link_to_tweet',
        ),
        migrations.AddField(
            model_name='twitter',
            name='url_to_tweet',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
