# Generated by Django 4.1.3 on 2022-11-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_snippet_language_alter_snippet_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='author_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='tweet_id',
            field=models.BigIntegerField(),
        ),
    ]
