# Generated by Django 4.1.3 on 2022-11-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_alter_twitter_author_id_alter_twitter_tweet_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
